# Generated by Django 4.1.7 on 2023-06-15 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_ue_type'),
        ('main', '0004_fichedepaie_information_paiement_and_more'),
    ]

    operations = [
    ]
