# Generated by Django 4.1.7 on 2023-06-15 10:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_merge_20230615_1014'),
    ]

    operations = [
        migrations.AddField(
            model_name='semestre',
            name='anneescolaire',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.anneeuniversitaire', verbose_name='Année universitaire'),
            preserve_default=False,
        ),
    ]
