# Generated by Django 4.2.2 on 2023-06-16 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_remove_matiere_heures_ue_semestre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personnel',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
