# Generated by Django 4.2.2 on 2023-06-16 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_personnel_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personnel',
            name='id',
            field=models.CharField(blank=True, max_length=12, primary_key=True, serialize=False),
        ),
    ]
